[package]
name = "frog_gopher"
version = "0.3.4"
authors = ["Perl I. W. <support@frog.tips>"]

[dependencies]
log = "0.3.6"
itertools = "0.4.13"
hyper = "0.10.5"
rustc-serialize = "0.3.19"
getopts = "0.2"
time = "0.1"
reqwest = "0.5.0"
